FORMAT: 1A
HOST: http://cloud.feedly.com/v3

# Feedly API
blueprint for Feedly api to manage RSS subscriptions

# Feedly API Root [/]

# Group Feeds
resources related to *Feedly Feeds*

## Feed [/feeds/:{feedId}]
Feed is a RSS feed resource

+ Parameters
    + feedId (string) ... Get the metadata about a specific feed
    
+ Model (application/json)

    + Body
    
            {
              "featured": false,
              "language": "en",
              "title": "Engadget",
              "id": "feed/http://feeds.engadget.com/weblogsinc/engadget",
              "sponsored": false,
              "subscribers": 123,
              "curated": false,
              "velocity": 180.3,
              "topics": [
                "tech",
                "gadgets"
              ],
              "state": "alive",
              "website": "http://www.engadget.com/"
            }
            
### Retrieve a single Feed metadata [GET]
+ Response 200

    [Feed][]




# Group Subscriptions

## Subscriptions [/subscriptions]

+ Model (application/json)

    + Body 

            [
              {
                "sortid": "26152F8F",
                "title": "Design Milk",
                "updated": 1367539068016,
                "id": "feed/http://feeds.feedburner.com/design-milk",
                "categories": [
                  {
                    "id": "user/c805fcbf-3acf-4302-a97e-d82f9d7c897f/category/design",
                    "label": "design"
                  },
                  {
                    "id": "user/c805fcbf-3acf-4302-a97e-d82f9d7c897f/category/global.must",
                    "label": "must reads"
                  }
                ],
                "visualUrl": "http://pbs.twimg.com/profile_images/1765276661/DMLogoTM-carton-icon-facebook-twitter_bigger.jpg",
                "added": 1367539068016,
                "website": "http://design-milk.com"
              }
            ]
            
        
### Get all user's subscriptions, user must be authenticated [GET]
+ Response 200

    [Subscriptions][]
    
    
# Group Authentication


## Auth [/auth/auth{?response_type,client_id,redirect_url,scope,state}]

+ Parameters

    + response_type (string) ... Indicates the type of token requested. At this time, this field will always have the value code
    + client_id (string) ... Indicates the client that is making the request. The value passed in this parameter must exactly match the value set during the partnership program.
    + redirect_url (string) ... Determines where the response is sent. The value of this parameter must exactly match one of the values set during the partnership program (including the http or https schemes, case, and trailing ‘/’). Make sure this parameter is URL-encoded!
    + scope (string) ... e.g. https://cloud.feedly.com/subscriptions
    + state (optional, string) ... Indicates any state which may be useful to your application upon receipt of the response. The feedly Authorization Server roundtrips this parameter, so your application receives the same value it sent. Possible uses include redirecting the user to the correct resource in your site, nonces, and cross-site-request-forgery mitigations. Make sure this parameter is URL-encoded!
    

+ Model

    + Body
    

### get the code to exchange with access token later [GET]
+ Response 300

    + Headers
        
            Location: http://localhost?code=AQAA7rJ7InAiOjEsImEiOiJmZWVk&state=state.passed.in
    
        
    
        
## Token  [/auth/token{?response_type,code,client_id,client_secret,redirect_uri,state,grant_type}]


+ Parameters

    + response_type (string) ... Indicates the type of token requested. At this time, this field will always have the value code
    + code (string) ... The code returned from the /auth/auth call
    + client_id (string) ... The clientId obtained during application registration
    + client_secret (string) ... The client secret obtained during application registration
    + redirect_uri (string) ... The URI registered with the application (make sure this parameter is URL-encoded!)
    + state (string) ... Indicates any state which may be useful to your application upon receipt of the response. The feedly Authorization Server roundtrips this parameter, so your application receives the same value it sent. Possible uses include redirecting the user to the correct resource in your site, nonces, and cross-site-request-forgery mitigations.
    + grant_type (string) ... authorization_code


+ Model (application/json)

    + Body
    
              {
                "id": "c805fcbf-3acf-4302-a97e-d82f9d7c897f",
                "refresh_token": "AQAA7rJ7InAiOjEsImEiOiJmZWVk...",
                "plan": "standard",
                "access_token": "AQAAF4iTvPam_M4_dWheV_5NUL8E...",
                "expires_in": 3920,
                "state": "...",
                "token_type": "Bearer"
              }

### exchange the code for an access token [POST]

+ Response 200

    [Token][]
    
        





